FROM tiangolo/uwsgi-nginx-flask:python3.12
COPY --from=docker.io/astral/uv /uv /uvx /bin/
ENV UV_PROJECT_ENVIRONMENT=/usr/local/
RUN touch README.md
COPY pyproject.toml uv.lock ./
COPY clasificahumor clasificahumor
RUN uv sync --no-default-groups --inexact --locked
COPY uwsgi.ini prestart.sh ./
COPY uwsgi.conf /etc/nginx/conf.d/
